#!/usr/bin/env bash

NPM_PKGS=$(npm list -g)
if [[ $NPM_PKGS == *"yarn"* ]]; then
    yarn install && yarn tauri build
else
    npm install -g yarn && yarn install && yarn tauri build && npm uninstall -g yarn
fi

mkdir -p bundle
cp src-tauri/target/release/bundle/* bundle/

rm -rf !("bundle")